### ISSUE TITLE
How do you get APS dataset's keyword attribute?

### ISSUE THREAD

**Issue by hcmdgh** [songjiang0909/HINTS_code#3]
Hello! When I visit https://journals.aps.org/datasets to download the raw APS dataset, I dont find anything about "keyword". But in your work, you use "keyword" as a node type. So how do you get that?

**Comment by songjiang0909** [comment]
Hi @hcmdgh, we generate the keywords of APS datasets using the method proposed in _Shang et al, Automated phrase mining from massive text corpora_, you can refer to the public [repo](https://github.com/shangjingbo1226/AutoPhrase). We basically use the keywords extracted by this method from the paper titles. The details of how we generate them can be found in datasets description of section 4.1.

**Comment by hcmdgh** [comment]
That's it, thanks.
